services:
  - type: web
    name: zeroexcuses-nlp-api
    env: python
    buildCommand: |
      pip install -r requirements.txt
      ./download_model.sh
    startCommand: PYTHONPATH=. uvicorn app.main:app --host 0.0.0.0 --port $PORT
    autoDeploy: true

